config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'

  resources :events, only: [:index]
  resources :reviews, only: [:index, :show]

  namespace :admin do
    get '/' => 'dashboards#index'
    resources :events
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_images

  accepts_nested_attributes_for :event_images, allow_destroy: true
end

app/models/event_image.rb
class EventImage < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :review_images

  accepts_nested_attributes_for :review_images, allow_destroy: true
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :review

  mount_uploader :image, ImageUploader
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController
  def index

  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @event.event_images.build
  end

  def create
    @event = Event.new(event_params)
    if params[:event][:event_images_attributes]["0"][:image].present?
      params[:event][:event_images_attributes]["0"][:image].each do |image|
        @event.event_images.new(image: image)
      end
    end
    @event.save(event_params)

    redirect_to admin_events_path, notice: '作成しました'
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to admin_events_path, notice: '更新しました'
    else
      render :index
    end
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path, notice: '削除しました'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :content, :note, :video_path, event_images_attributes: [])
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < AdminController
  before_action :set_review, only: [:edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @review.review_images.build
  end

  def create
    @review = Review.new(review_params)
    if params[:review][:review_images_attributes]["0"][:image].present?
      params[:review][:review_images_attributes]["0"][:image].each do |image|
        @review.review_images.new(image: image)
      end
    end
    @review.save(review_params)

    redirect_to admin_reviews_path, notice: '作成しました'
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to admin_reviews_path, notice: '更新しました'
    else
      render :index
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path, notice: '削除しました'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :note, review_images_attributes: [])
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :http_basic_authenticate
  # before_action :authenticate_admin_user!
  layout 'admin/layouts/application'

  def index
    redirect_to admin_dashboard_path
  end

  private

    def http_basic_authenticate
      return if Rails.env.development?
      authenticate_or_request_with_http_basic('') do |name, password|
        name == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  before_action :set_view_path

  private

    def set_view_path
      path =  request.smart_phone? ? 'sp' : 'pc'
      prepend_view_path(Rails.root + 'app/views' + path)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(created_at: :desc).page(params[:page]).per(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.order(created_at: :desc).page(params[:page]).per(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def vimeo_iframe(vimeo_num)
    iframe = content_tag(
      :iframe,
      '',
      width: 640,
      height: 360,
      src: "https://player.vimeo.com/video/#{vimeo_num}?loop=1&title=0&byline=0&portrait=0",
      frameborder: 0,
      allow: 'autoplay',
      fullscreeen: 'allowfullscreen'
    )
    content_tag(:div, iframe, class: 'vimeo-container')
  end
end

app/views/admin/events/_form.html.erb
<%= form_for([:admin, event]) do |f| %>
  <div class="event_container">
    <div class="event_box">

      <div class="event_left">
        <p class="event_left__item">
          <% if action_name == 'edit' %>
            <% event.event_images.each do |event_image| %>
              <%= image_tag(event_image.image.url) %>
            <% end %>
          <% end %>
          <%= f.fields_for :event_images do |event_image| %>
            <%= event_image.file_field :image, multiple: true %>
          <% end %>
        </p>
      </div>
      <div class="event_right">
        <div class="event_right__item">
          <div class="event_title">
            <p>タイトル</p>
            <p><%= f.text_field :title %></p>
          </div>
          <div class="event_content">
            <p>内容</p>
            <%= f.text_area :content, rows: 30 %>
          </div>
        </div>
      </div>
    </div>

    <div class="video_path">
      <!-- <p>iframe （動画があれば）</p> -->
      <%#= f.text_area :video_path, rows: 10 %>
    </div>

    <div class="submit">
      <p><%= f.submit title, class: 'submit' %></p>
    </div>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<div id="event">
  <h1 class="top-title">WORKSHOP/EVENT 編集画面</h1>
  <%= render 'form', event: @event, title: '編集する' %>
</div>

app/views/admin/events/index.html.erb
<div class="text_center">
  <p class="mb30"><%= link_to '新規作成する', new_admin_event_path %></p>

  <h4>イベント一覧</h4>
  <% @events.each do |event| %>
    <p><%= event.title %>
      <%= link_to '編集する', edit_admin_event_path(event)%> /
      <%= link_to '削除する', admin_event_path(event), method: :delete, data: { confirm: '本当に削除しますか?' } %>
    </p>
  <% end %>
</div>

app/views/admin/events/new.html.erb
<div id="event">
  <h1 class="top-title">WORKSHOP/EVENT 新規作成</h1>
  <%= render 'form', event: @event, title: '新規作成' %>
</div>

app/views/admin/layouts/_header.html.erb
<header>
  <div id="header_left">
      <div class="head_left">
          <ul id="nav">
              <li>管理画面</li>
              <li><%= link_to 'EVENT', admin_events_path %></li>
              <li><%= link_to 'REVIEW', admin_reviews_path %></li>
              <li><%= link_to 'ホーム', root_path %></li>
          </ul>
      </div>
  </div>

  <div id="header_right"></div>
</header>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなで月に行く前に</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'pc/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'pc/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/layouts/header' %>
    <div id="main">
      <div id="left_side">
        <%= yield %>
      </div>
      <%= render 'admin/layouts/right_side' %>
      <%= render 'admin/layouts/footer' %>
    </div><!--  main   -->
  </body>
</html>

app/views/admin/reviews/_form.html.erb
<%= form_for([:admin, review]) do |f| %>
  <div class="review_container">
    <div class="review_box">

      <div class="review_left">
        <p class="review_left__item">
          <% if action_name == 'edit' %>
            <% review.review_images.each do |review_image| %>
              <%= image_tag(review_image.image.url) %>
            <% end %>
          <% end %>
          <%= f.fields_for :review_images do |review_image| %>
            <%= review_image.file_field :image, multiple: true %>
          <% end %>
        </p>
      </div>
      <div class="review_right">
        <div class="review_right__item">
          <div class="review_title">
            <p>タイトル</p>
            <p><%= f.text_field :title %></p>
          </div>
          <div class="review_content">
            <p>内容</p>
            <%= f.text_area :content, rows: 30 %>
          </div>
        </div>
      </div>
    </div>

    <div class="video_path">
      <!-- <p>iframe （動画があれば）</p> -->
      <%#= f.text_area :video_path, rows: 10 %>
    </div>

    <div class="submit">
      <p><%= f.submit title, class: 'submit' %></p>
    </div>
  </div>
<% end %>

app/views/admin/reviews/edit.html.erb
<div id="review">
  <h1 class="top-title">WORKSHOP/review 編集画面</h1>
  <%= render 'form', review: @review, title: '編集する' %>
</div>

app/views/admin/reviews/index.html.erb
<div class="text_center">
  <p class="mb30"><%= link_to '新規作成する', new_admin_review_path %></p>

  <h4>Review一覧</h4>
  <% @reviews.each do |review| %>
    <p><%= review.title %>
      <%= link_to '編集する', edit_admin_review_path(review)%> /
      <%= link_to '削除する', admin_review_path(review), method: :delete, data: { confirm: '本当に削除しますか?' } %>
    </p>
  <% end %>
</div>

app/views/admin/reviews/new.html.erb
<div id="review">
  <h1 class="top-title">Review 新規作成</h1>
  <%= render 'form', review: @review, title: '新規作成' %>
</div>

app/views/pc/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなで月に行く前に</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'pc/application', media: 'all' %>
    <%= javascript_include_tag 'pc/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <div id="main">
      <div id="left_side">
        <%= yield %>
      </div>
      <%= render 'partials/right_side' %>
      <%= render 'partials/footer' %>
    </div><!--  main   -->
  </body>
</html>

app/views/sp/events/index.html.erb
<div id="event">
  <h1 class="top-title">WORKSHOP/EVENT</h1>
  <% @events.each do |event| %>
    <div class="event_container">
      <div class="event_number">
        <h1>みんなで月に行く前に Vol.<%= event.id %></h1>
      </div>
      <div class="event_box">

        <div class="event_left">
          <p class="event_left__item">
            <% if event.event_images.present? %>
              <% event.event_images.each do |event_image| %>
                <%= image_tag(event_image.image.url) %>
              <% end %>
            <% end %>
          </p>
        </div>
        <div class="event_right">
          <div class="event_right__item">
            <div class="event_title">
              <p><%= event.title %></p>
            </div>
            <div class="event_content">
              <p><%= simple_format(event.content) %></p>
            </div>
          </div>
        </div>
      </div>
      <% if event.video_path.present? %>
        <div class="video_path">
          <%= vimeo_iframe(event.video_path) %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="paginate">
  <p class="paginate-left"><%= link_to_prev_page @events, 'Next Event' %></p>
  <p class="paginate-right"><%= link_to_next_page @events, 'Previous Event' %></p>
</div>

app/views/sp/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなで月に行く前に</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'sp/application', media: 'all' %>
    <%= javascript_include_tag 'sp/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <div id="main">
      <div id="left_side">
        <%= yield %>
      </div>
      <%= render 'partials/right_side' %>
      <%= render 'partials/footer' %>
    </div><!--  main   -->
  </body>
</html>

app/views/sp/pages/top.html.erb
<div class="main_box">
    <div class="main_box__item">
        <h2 class="content">
            ぼくらはいったい地球のことをどのくらい知っているだろうか<br/> あるいは アウトドアでの行動・生活・観察についての一省察野帖<br/> または
        </h2>
    </div>
    <div class="arrow">
      <%= image_tag 'arrow.gif', alt: 'arrow' %>
    </div>
</div>

<div id="about">
  <div class="about" class="box_about">
    <!-- <h1>ABOUT</h1> -->
    <div class="box__item__about">
        <p>こんな不思議な書き出しで始まるタイトル『みんなで月に行くまえに』という本があります。
        私たちはこの素敵な読本から刺激を受けて同名の野外ワークショップ企画を起こすことにいたしました。
        </p>
        <p>
        しかし残念ながら私たちの職業はデザイナー、音楽家、そしてカフェオーナー、誰も本格的なサバイバル技術を人に教えることは出来ません。 けれども自然を感じたり、楽しむことなら得意です。何か作ったり、表現するのも大好きです。
        </p>
        <p>「みんなで月に行くまえに」という名前のこのワークショップ、 これは、私たちなりの同書への返答であり、解釈であり、そして皆さんへの招待状でもあります。
        </p>
        <p>人類が宇宙を旅したり、移住したりするのも遠い未来じゃありません。 やがて来る宇宙の時代。みんなで月に行くまえに、 １冊の本を手引きに携え、もっと地球で遊びませんか？
        </p>
        <!-- <div class="about_member"> -->
        <div class="about_member">
            <p><a href="https://himadacoffee.blogspot.com/" target="_blank">齊藤啓介 / HIMADA COFFEE - 店主</a><br/>
                <a href="http://hammockmassage-chilling.com" target="_blank">小池信行/ Chilling - Hammock Massage</a><br/>
                <a href="https://www.shop-sunshine-to-you.com/" target="_blank">木原佐知子 / sunshine to you! - デザイナー</a><br/>
                <a href="https://sphontik.com/" target="_blank">木原健児 / 音楽家</a></p>
        </div>
        <!-- </div> -->
    </div>
  </div>
</div>

app/views/sp/partials/_footer.html.erb
<div class="footer">
<p>Before go to the moon. All Rights Reserved.</p>
</div>

app/views/sp/partials/_header.html.erb
<header>
  <div id="header_left">
      <div class="head_left">
          <ul id="nav">
              <li><%= link_to 'ABOUT', root_path %></li>
              <li><%= link_to 'WORKSHOP/EVENT', events_path %></li>
              <li><%= link_to 'REVIEW', reviews_path %></li>
          </ul>
      </div>
  </div>

  <div id="header_right"></div>
</header>

app/views/sp/partials/_right_side.html.erb
<div id="right_side">
    <div class="title_box">
        <h1 class="main_title"><a href="index.html">みんなで月に行くまえに</a></h1>
    </div>
</div>

app/views/sp/reviews/index.html.erb
<section id="review">
  <div class="review_box">
    <h1>BOOK/REVIEW</h1>
    <% @reviews.each do |review| %>
      <div class="review_image">
        <% if review.review_images.present? %>
          <p><%= image_tag review.review_images.first.image.url, width: '100%' %></p>
        <% end %>
      </div>
      <div class="review_content_box">
        <div class="review_title">
          <h2><%= "#{review.id}. #{review.title}" %></h2>
        </div>
        <div class="review_content">
          <p><%= simple_format(review.content) %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="paginate">
    <p class="paginate-left"><%= link_to_prev_page @reviews, 'Next Review' %></p>
    <p class="paginate-right"><%= link_to_next_page @reviews, 'Previous Review' %></p>
  </div>
</section>

app/views/sp/reviews/show.html.erb
<section id="review">
  <div class="review_box">
    <h1>BOOK/REVIEW</h1>
    <div class="review_image">
      <p><%= image_tag 'bgm_main.JPG', width: '100%' %></p>
    </div>
    <div class="review_content_box">
      <div class="review_title">
        <h2><%= "#{@review.id}. #{@review.title}" %></h2>
      </div>
      <div class="review_content">
        <p><%= simple_format(@review.content) %></p>
      </div>
    </div>
  </div>
</section>